// COMPONENTS AND DATA IMPORT

/*HEADER START
HEADER END

HERO START
HERO END

INFO SQUARES START
INFO SQUARES END

CUSTOMIZATION START
CUSTOMIZATION END

PAYMENT METHODS START
PAYMENT METHODS END

PRODUCT RATING REVIEWS START*/
import { customerReviewsData } from './data/customer-reviews.js';
import { CustomerReviews } from './components/customer-reviews.js';
import { Carousel } from './components/carousel/Carousel';
/*
PRODUCT RATING REVIEWS END

SOLUTIONS START
SOLUTIONS END

START USING START
START USING END

CUSTOMER REVIEWS START
CUSTOMER REVIEWS END

PREMIUM FEATURES START
PREMIUM FEATURES END

LOGO GALLERY START
LOGO GALLERY END

FOOTER START
FOOTER END
*/
// COMPONENTS EXECUTION
new Carousel ({
    data: customerReviewsData,
    renderEngine: CustomerReviews,
    breakpoints: [800, 1100]
});